[project]
name = "esmj"
version = "0.1.0"
description = "JAX translation of ESMC"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "equinox>=0.12.1",
    "esm>=3.2.0",
    "jax>=0.6.0",
    "jaxtyping>=0.3.2",
    "numpy>=2.2.5",
]

[tool.uv]
package = true
